import * as THREE from 'three';
import { gsap } from 'gsap';
import { TEAM, CLASSES, WEAPONS, MISSIONS, COSMETICS, PASSIVE_SKILLS, ACTIVE_SKILLS, rollDrop } from '../data/gameData.js';
import { SaveSystem } from './SaveSystem.js';
import { Input } from './Input.js';
import { HUD } from './HUD.js';
import { MaterialLibrary } from './Materials.js';
import { EntityFactory } from './EntityFactory.js';
import { World } from './World.js';
import { DBuilder } from './DBuilder.js';
import { ParticleSystem } from './ParticleSystem.js';
import { CombatSystem } from './CombatSystem.js';
import { AIController } from './AIController.js';
import { AudioSystem } from './AudioSystem.js';

const pick = list => list[Math.floor(Math.random() * list.length)];

export class Game{
  constructor(mount){this.mount=mount;this.screen=document.querySelector('#screen');this.save=new SaveSystem();this.input=new Input(mount);this.hud=new HUD();this.audio=new AudioSystem(this.save.data.settings.volume);this.lastFrame=performance.now()/1000;this.state='menu';this.running=false;this.entities=[];this.allies=[];this.enemies=[];this.kills=0;this.elapsed=0;this.spawnTimer=0;this.lockTarget=null;this.hoverEntity=null;this.bindUI()}
  boot(){this.setupRenderer();this.showMenu();this.loop()}
  setupRenderer(){this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance',stencil:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=this.save.data.settings.shadows;this.renderer.shadowMap.type=THREE.PCFShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;this.mount.appendChild(this.renderer.domElement);this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,180);this.camera.position.set(0,24,23);addEventListener('resize',()=>this.resize());}
  bindUI(){this.screen.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;this.audio.play('pickup',1.1);if(action==='start')this.startMission('assault');else if(action==='missions')this.showMissions();else if(action.startsWith('mission:'))this.startMission(action.slice(8));else if(action==='hub')this.showHub();else if(action==='menu')this.showMenu();else if(action==='settings')this.showSettings();else if(action==='shop')this.showShop();else if(action==='dbuild')this.showDBuild();else if(action==='casino')this.playCasino();else if(action==='reset'){this.save.reset();this.showMenu()}else if(action.startsWith('gear:'))this.buyGear(action.slice(5));else if(action.startsWith('cos:'))this.handleCosmetic(action.slice(4))});this.screen.addEventListener('input',e=>{if(!e.target.dataset.setting)return;const key=e.target.dataset.setting,value=e.target.type==='checkbox'?e.target.checked:Number(e.target.value);this.save.setSetting(key,value);if(key==='volume')this.audio.setVolume(value);if(key==='shadows'&&this.renderer)this.renderer.shadowMap.enabled=value})}
  showMenu(){this.endRuntime();this.state='menu';this.screen.innerHTML=`<main class="menu"><h1 class="logo">Destructo</h1><p class="subtitle">Build the squad. Break the battlefield.</p><div class="menu-actions"><button class="btn primary" data-action="start">QUICK DEPLOY</button><button class="btn" data-action="missions">MISSION BOARD</button><button class="btn" data-action="hub">CENTRAL HUB</button><button class="btn" data-action="settings">SETTINGS</button></div><div class="meta"><span>WASD MOVE · SPACE JUMP · MOUSE FIRE · HOLD RMB LOCK-AIM · E CRATE · F MATERIALIZE · Q SKILL · TAB SQUAD</span><span>${this.save.data.missionsWon} VICTORIES · ${this.save.data.chips} CHIPS</span></div></main>`}
  showMissions(){this.endRuntime();this.state='missions';this.screen.innerHTML=`<main class="menu"><div class="screen-title"><div><span class="eyebrow">FIRST DIMENSION</span><h2>MISSION BOARD</h2></div></div><div class="hub-grid">${Object.values(MISSIONS).map(m=>`<article class="hub-card"><h3>${m.name.toUpperCase()}</h3><p>${m.briefing}</p><button class="btn ${m.id==='assault'?'primary':''}" data-action="mission:${m.id}">DEPLOY · ${m.reward} CHIPS</button></article>`).join('')}</div><button class="btn" style="margin-top:22px" data-action="menu">BACK</button></main>`}
  showHub(){this.endRuntime();this.state='hub';this.screen.innerHTML=`<main class="menu"><div class="screen-title"><div><span class="eyebrow">CENTRAL MILITARY HUB</span><h2>BETWEEN BATTLES</h2></div><strong>${this.save.data.chips} CHIPS</strong></div><div class="hub-grid"><article class="hub-card"><h3>MARKETPLACE</h3><p>License combat gear for future operations.</p><button class="btn" data-action="shop">BROWSE GEAR</button></article><article class="hub-card"><h3>CRATE CASINO</h3><p>Risk 100 chips. Match charged crates to win prototype payouts.</p><button class="btn" data-action="casino">SPIN · 100</button></article><article class="hub-card"><h3>D-BUILD STUDIO</h3><p>Customize your team's Destructos with hats and skins. ${this.save.data.totalKills} eliminations across ${this.save.data.missionsWon} victories.</p><button class="btn primary" data-action="dbuild">OPEN STUDIO</button></article></div><button class="btn" style="margin-top:22px" data-action="menu">BACK</button></main>`}
  showSettings(){const s=this.save.data.settings;this.screen.innerHTML=`<main class="menu"><div class="screen-title"><h2>SETTINGS</h2></div><div class="settings"><label>DYNAMIC SHADOWS <input type="checkbox" data-setting="shadows" ${s.shadows?'checked':''}></label><label>CAMERA SHAKE <input type="checkbox" data-setting="cameraShake" ${s.cameraShake?'checked':''}></label><label>VOLUME <input type="range" min="0" max="1" step=".05" value="${s.volume}" data-setting="volume"></label></div><button class="btn" style="margin-top:22px" data-action="menu">BACK</button></main>`}
  showShop(){const gear=[['magnet','MAGNETIC GLOVES',900],['rearPlate','BALLISTIC REAR PLATE',1100],['jetpack','ROCKET JETPACK',1800]];this.screen.innerHTML=`<main class="menu"><div class="screen-title"><h2>MARKETPLACE</h2><strong>${this.save.data.chips} CHIPS</strong></div><div class="menu-actions">${gear.map(([id,name,price])=>`<button class="btn" data-action="gear:${id}" ${this.save.data.gear.includes(id)?'disabled':''}>${name}<br><small>${this.save.data.gear.includes(id)?'EQUIPPED':price+' CHIPS'}</small></button>`).join('')}</div><button class="btn" style="margin-top:22px" data-action="hub">BACK</button></main>`}
  // D-Build studio: buy + equip cosmetics for your team's Destructos
  showDBuild(){const owned=this.save.data.cosmetics,eq=this.save.data.equipped;const card=c=>{const isOwned=owned.includes(c.id),equipped=eq[c.kind]===c.id;return `<button class="btn cosmetic ${equipped?'equipped':''}" data-action="cos:${c.id}">${c.name.toUpperCase()}<br><small>${c.kind.toUpperCase()} · ${equipped?'EQUIPPED':isOwned?'TAP TO EQUIP':c.price+' CHIPS'}</small></button>`};this.screen.innerHTML=`<main class="menu"><div class="screen-title"><div><span class="eyebrow">D-BUILD STUDIO</span><h2>TEAM COSMETICS</h2></div><strong>${this.save.data.chips} CHIPS</strong></div><h3 class="shop-section">HATS</h3><div class="menu-actions">${COSMETICS.filter(c=>c.kind==='hat').map(card).join('')}</div><h3 class="shop-section">BODY SKINS</h3><div class="menu-actions">${COSMETICS.filter(c=>c.kind==='skin').map(card).join('')}</div><button class="btn" style="margin-top:22px" data-action="hub">BACK</button></main>`}
  handleCosmetic(id){const c=COSMETICS.find(x=>x.id===id);if(!c)return;if(this.save.data.cosmetics.includes(id)){this.save.equipCosmetic(c.kind,id);this.audio.play('build')}else if(this.save.buyCosmetic(id,c.price))this.audio.play('build');else{this.screen.querySelector('.screen-title strong').textContent='INSUFFICIENT CHIPS';return}this.showDBuild()}
  buyGear(id){const prices={magnet:900,rearPlate:1100,jetpack:1800};if(this.save.buyGear(id,prices[id])){this.audio.play('build');this.showShop()}else this.screen.querySelector('.screen-title strong').textContent='INSUFFICIENT CHIPS'}
  playCasino(){if(!this.save.spend(100)){this.showHub();return}const roll=Math.random(),reward=roll>.92?1500:roll>.7?250:0;if(reward)this.save.earn(reward);this.screen.innerHTML=`<main class="menu mission-end"><span class="eyebrow">CRATE SPINNER</span><h2>${reward?'WINNER!':'SCRAPPED'}</h2><div class="stat-row"><div><strong>${reward||0}</strong><span>CHIPS WON</span></div><div><strong>${this.save.data.chips}</strong><span>BALANCE</span></div></div><button class="btn primary" data-action="hub">CONTINUE</button></main>`}
  async startMission(id='assault'){this.mission=MISSIONS[id]||MISSIONS.assault;this.screen.innerHTML=`<main class="menu mission-end"><h2>DEPLOYING</h2><p class="subtitle">${this.mission.name.toUpperCase()}…</p></main>`;await this.createMission();this.screen.innerHTML='';this.hud.show(true);this.input.enabled=true;this.state='mission';this.lastFrame=performance.now()/1000}
  teamCosmetics(){const eq=this.save.data.equipped;return{hat:eq.hat||undefined,skin:eq.skin||undefined}}
  async createMission(){this.disposeScene();this.scene=new THREE.Scene();this.materials=await new MaterialLibrary(this.renderer,this.save.data.settings).load();this.factory=new EntityFactory(this.scene,this.materials);this.addLights();this.world=new World(this.scene,this.materials,this.factory).build();this.entities=[this.world.blueFactory,this.world.redFactory,...this.world.destructibles,...this.world.wildlife];this.allies=[];this.enemies=[];this.abilityZones=[];this.objectiveProgress=0;this.lockTarget=null;this.hoverEntity=null;this.player=this.factory.createUnit('scout','blue',new THREE.Vector3(-28,0,-22),true,this.teamCosmetics());this.player.rearPlate=this.save.data.gear.includes('rearPlate');this.player.magneticGloves=this.save.data.gear.includes('magnet');this.player.jetpack=this.save.data.gear.includes('jetpack');this.player.ammo=90;this.allies.push(this.player);this.entities.push(this.player);[['medic',-31,-19],['gunner',-25,-20]].forEach(([c,x,z])=>this.addUnit(c,'blue',new THREE.Vector3(x,0,z)));[['scout',27,22],['gunner',29,18],['commando',23,27],['medic',35,21],['sniper',20,20],['engineer',37,26]].forEach(([c,x,z])=>this.addUnit(c,'red',new THREE.Vector3(x,0,z)));this.particles=new ParticleSystem(this.scene);this.combat=new CombatSystem(this.scene,this.particles,()=>this.entities,this.handleDeath.bind(this),this.handleDamage.bind(this));this.builders={blue:new DBuilder(this.world,this.factory,this.handleBuild.bind(this),'blue',this.world.builderPositions.blue),red:new DBuilder(this.world,this.factory,this.handleBuild.bind(this),'red',this.world.builderPositions.red)};this.builder=this.builders.blue;this.ai=new AIController(this.world,this.combat,this.builders,u=>this.executeActiveSkill(u));this.kills=0;this.elapsed=0;this.spawnTimer=15;this.crateTimer=9;this.camera.position.copy(this.player.group.position).add(new THREE.Vector3(0,21,20));this.camera.lookAt(this.player.group.position);this.hud.el.objective.textContent=this.mission.objective;}
  addLights(){const hemi=new THREE.HemisphereLight(0xd8f0ff,0x3f5a36,.95);this.scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff6d8,1.7);sun.position.set(-24,38,-18);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=sun.shadow.camera.bottom=-48;sun.shadow.camera.right=sun.shadow.camera.top=48;sun.shadow.bias=-.0008;this.scene.add(sun)}
  addUnit(classId,team,pos,opts={}){const unit=this.factory.createUnit(classId,team,pos,false,team==='blue'?{...this.teamCosmetics(),...opts}:opts);(team==='blue'?this.allies:this.enemies).push(unit);this.entities.push(unit);return unit}
  update(dt,time){if(this.state!=='mission')return;dt=Math.min(dt,.033);this.elapsed+=dt;this.updatePlayer(dt);for(const e of this.allies)this.ai.update(e,dt,this.allies,this.enemies,this.player);for(const e of this.enemies)this.ai.update(e,dt,this.allies,this.enemies,this.player);this.combat.update(dt);this.world.update(time,dt);this.updateWildlife(dt);this.updateObjective(dt);this.updateAbilityZones(dt);this.updatePickups(dt);this.particles.update(dt,this.camera);for(const e of [...this.allies,...this.enemies]){for(const key of ['abilityCooldown','statusTimer','overdriveTimer','rallyTimer','barrierTimer','frenzyTimer'])e[key]=Math.max(0,(e[key]||0)-dt);if(e.buffs)for(const key of Object.keys(e.buffs))e.buffs[key]=Math.max(0,e.buffs[key]-dt);if(e.freeze>0&&e===this.player)e.freeze=Math.max(0,e.freeze-dt);if(e.cloakTimer>0){e.cloakTimer=Math.max(0,e.cloakTimer-dt);if(e.cloakTimer===0)this.setCloak(e,false)}if(!e.dead&&e.passive?.id==='regen')e.hp=Math.min(e.maxHp,e.hp+dt*2.5);if(!e.dead&&e.passive?.id==='healeraura'){const friends=e.team==='blue'?this.allies:this.enemies;for(const f of friends)if(!f.dead&&f!==e&&f.group.position.distanceTo(e.group.position)<6)f.hp=Math.min(f.maxHp,f.hp+dt*1.5)}if(Number.isFinite(e.maxMp))e.mp=Math.min(e.maxMp,e.mp+dt*3.5*(e.passive?.id==='manabattery'?1.6:1));if(e.type==='unit'){this.positionCarriedCrate(e);this.factory.animateUnit(e,time,dt)}}this.crateTimer-=dt;if(this.crateTimer<=0&&this.world.crates.length<16){this.world.airdropCrate();this.crateTimer=7+Math.random()*6}this.spawnTimer-=dt;if(this.spawnTimer<=0&&this.enemies.filter(e=>!e.dead).length<7&&!this.world.redFactory.dead){this.addUnit(Math.random()>.5?'scout':'gunner','red',this.world.redFactory.group.position.clone().add(new THREE.Vector3(-5,0,-4)));this.spawnTimer=this.mission.type==='capture'?9:14}this.updateCamera(dt);this.updateHover();this.hud.update(this.player,this.world.redFactory,this.allies.filter(e=>!e.dead).length,this.save.data.chips,this.builder.values());this.input.endFrame()}
  // carried crates ride out front, held in both hands
  positionCarriedCrate(e){const c=e.carriedCrate;if(!c)return;c.group.visible=true;const forward=new THREE.Vector3(Math.sin(e.group.rotation.y),0,Math.cos(e.group.rotation.y));c.group.position.copy(e.group.position).addScaledVector(forward,1.25);c.group.position.y=e.group.position.y+.82;c.group.rotation.y=e.group.rotation.y}
  updatePlayer(dt){if(this.input.consume('Tab'))this.switchPlayer();const p=this.player;if(p.dead)return;p.fireCooldown=Math.max(0,p.fireCooldown-dt);if(p.stun>0){p.stun-=dt;p.group.position.addScaledVector(p.velocity,dt);p.velocity.multiplyScalar(Math.pow(.15,dt));return}const axis=this.input.axis(),speed=p.classDef.speed*(p.statusTimer>0?1.6:1)*(p.rallyTimer>0?1.25:1)*(p.buffs.speed>0?1.55:1)*(this.world.isWater(p.group.position)?.5:1);p.velocity.x=THREE.MathUtils.lerp(p.velocity.x,axis.x*speed,Math.min(1,dt*14));p.velocity.z=THREE.MathUtils.lerp(p.velocity.z,axis.z*speed,Math.min(1,dt*14));p.group.position.x+=p.velocity.x*dt;p.group.position.z+=p.velocity.z*dt;
    // jump (Team Buddies hop) + optional jetpack sustain
    const grounded=p.group.position.y<=0.001;
    if(this.input.consume('Space')&&grounded){p.verticalVelocity=8.6*(p.passive?.id==='highjumper'?1.4:1);this.audio.play('pickup',1.6)}
    else if(p.jetpack&&this.input.keys.has('Space')&&!grounded&&p.mp>0){p.verticalVelocity=Math.min(6,(p.verticalVelocity||0)+dt*20);p.mp=Math.max(0,p.mp-dt*12)}
    p.verticalVelocity=(p.verticalVelocity||0)-dt*22;
    const before=p.group.position.y;p.group.position.y=THREE.MathUtils.clamp(p.group.position.y+p.verticalVelocity*dt,0,9);
    if(p.group.position.y===0&&p.verticalVelocity<0){if(before>.4)this.particles.impact(p.group.position.clone(),0xd8ccb0);p.verticalVelocity=0}
    this.world.clamp(p.group.position);this.updateAim(dt);if(this.input.mouse.down&&!p.carriedCrate){if(this.combat.shoot(p,p.aim))this.audio.play('shoot',.85+Math.random()*.25);else if(Number.isFinite(p.ammo)&&p.ammo<=0&&p.weaponId!=='pistol'&&p.fireCooldown<=0){p.weaponId='pistol';p.weapon=WEAPONS.pistol;this.hud.toast('OUT OF AMMO · PISTOL EQUIPPED',true)}}if(this.input.consume('KeyQ'))this.useAbility();this.handleInteraction();this.handleMaterialize();if(this.input.mouse.alt){this.commandPoint=p.group.position.clone().addScaledVector(p.aim,10);if(this.lockTarget){this.lockTarget=null;this.hud.toast('LOCK RELEASED')}this.input.mouse.alt=false}}
  handleMaterialize(){if(!this.input.consume('KeyF'))return;const p=this.player;
    if(this.builder.distanceTo(p.group.position)<4.2){const r=this.builder.manufacture();if(r)return;this.hud.toast('INVALID STACK — CLEAN TOWERS ONLY',true);return}
    // outside a builder: F cracks open a crate for field drops
    const crate=p.carriedCrate||this.nearestLooseCrate(3);if(crate){this.openCrate(crate);if(p.carriedCrate===crate)p.carriedCrate=null;return}
    this.hud.toast('NOTHING TO MATERIALIZE',true)}
  nearestLooseCrate(range){let best=null,dist=range;for(const c of this.world.crates){if(c.carried||c.placed||c.falling)continue;const d=c.group.position.distanceTo(this.player.group.position);if(d<dist){dist=d;best=c}}return best}
  // loose crate materialize: pops open and scatters pickups by rarity
  openCrate(crate){const i=this.world.crates.indexOf(crate);if(i>=0)this.world.crates.splice(i,1);const type=crate.crateType,pos=crate.group.position.clone().setY(0);this.audio.play('build');this.particles.burst(pos.clone().add(new THREE.Vector3(0,.8,0)),type.color,26,7);
    gsap.to(crate.group.scale,{x:1.35,y:1.5,z:1.35,duration:.12,yoyo:true,repeat:1,ease:'power2.out',onComplete:()=>{gsap.to(crate.group.scale,{x:.02,y:.02,z:.02,duration:.2,ease:'back.in(2)',onComplete:()=>this.world.scene.remove(crate.group)})}});
    let count=type.drops+(this.player.passive?.id==='packrat'?1:0);
    for(let n=0;n<count;n++){const drop=rollDrop();const offset=new THREE.Vector3((Math.random()-.5)*2.4,0,(Math.random()-.5)*2.4);const pickup=this.factory.createPickup(drop,pos.clone().add(offset));pickup.group.scale.setScalar(.01);gsap.to(pickup.group.scale,{x:1,y:1,z:1,duration:.3,delay:.1+n*.06,ease:'back.out(3)'});this.world.pickups.push(pickup)}}
  updatePickups(dt){const p=this.player;for(let i=this.world.pickups.length-1;i>=0;i--){const item=this.world.pickups[i];item.life-=dt;const range=(p.magneticGloves?2.6:1.6)*(p.passive?.id==='scavenger'?2:1);if(!p.dead&&item.group.position.distanceTo(p.group.position)<range){this.applyDrop(item.drop,p);this.scene.remove(item.group);this.world.pickups.splice(i,1);this.audio.play('pickup',1.2);continue}if(item.life<=0){this.scene.remove(item.group);this.world.pickups.splice(i,1)}}}
  applyDrop(drop,unit){switch(drop.id){case 'ammo':unit.ammo=(unit.ammo||0)+40;break;case 'health':unit.hp=Math.min(unit.maxHp,unit.hp+50);break;case 'mana':unit.mp=Math.min(unit.maxMp,unit.mp+40);break;case 'speed':unit.buffs.speed=drop.duration;break;case 'shield':unit.shield=Math.max(unit.shield,drop.shield);break;case 'damage':unit.buffs.damage=drop.duration;break;case 'rapid':unit.buffs.rapid=drop.duration;break;case 'chips':this.save.earn(100);break}this.hud.toast(drop.name.toUpperCase());this.spawnDamageNumber(unit.group.position,drop.name.toUpperCase(),'pickup')}
  updateWildlife(dt){const combatants=[...this.allies,...this.enemies].filter(e=>!e.dead);for(const w of this.world.wildlife){if(w.dead)continue;w.attackCooldown=Math.max(0,w.attackCooldown-dt);w.decisionTimer-=dt;let target=null;if(w.kind==='wolf'){let best=Infinity;for(const e of combatants){const d=e.group.position.distanceToSquared(w.group.position);if(d<best){best=d;target=e}}if(target&&best<100){const dir=target.group.position.clone().sub(w.group.position).setY(0),dist=dir.length();dir.normalize();w.velocity.lerp(dir.multiplyScalar(w.speed),dt*4);w.aim.copy(dir);if(dist<1.35&&w.attackCooldown<=0){this.combat.applyDamage(target,9,w,dir,2);if(target.passive?.id==='thorns')this.combat.applyDamage(w,1.35,target,dir.clone().negate(),1);w.attackCooldown=.8}}else target=null}else if(w.kind==='slime'){let best=Infinity;for(const c of this.world.crates){if(c.carried||c.placed||c.falling)continue;const d=c.group.position.distanceToSquared(w.group.position);if(d<best){best=d;target=c}}if(target){const dir=target.group.position.clone().sub(w.group.position).setY(0),dist=dir.length();dir.normalize();w.velocity.lerp(dir.multiplyScalar(w.speed),dt*3);if(dist<1.1){this.scene.remove(target.group);this.world.crates.splice(this.world.crates.indexOf(target),1);target=null}}}if(!target){if(w.decisionTimer<=0){w.decisionTimer=1.5+Math.random()*2;w.wanderAngle+=(Math.random()-.5)*2.4}w.velocity.lerp(new THREE.Vector3(Math.sin(w.wanderAngle),0,Math.cos(w.wanderAngle)).multiplyScalar(w.speed*.45),dt*2)}w.group.position.addScaledVector(w.velocity,dt);this.world.clamp(w.group.position);if(w.velocity.lengthSq()>.05)w.group.rotation.y=Math.atan2(w.velocity.x,w.velocity.z);if(w.kind==='slime')w.group.scale.y=.92+Math.sin(this.elapsed*7+w.wanderAngle)*.08}}
  updateObjective(dt){if(this.mission.type!=='capture'||this.world.redFactory.dead&&this.objectiveProgress>=this.mission.duration)return;const near=team=>team.filter(e=>!e.dead&&e.group.position.distanceTo(this.world.cavePosition)<6).length,blue=near(this.allies),red=near(this.enemies);if(blue>red&&blue>0)this.objectiveProgress=Math.min(this.mission.duration,this.objectiveProgress+dt);else this.objectiveProgress=Math.max(0,this.objectiveProgress-dt*.35);this.world.caveRing.material.color.setHex(blue>red&&blue>0?0x4cff8a:red>blue?0xff4b55:0x5bd9ff);this.hud.el.objective.textContent=`Hold the mineral cave · ${Math.ceil(this.mission.duration-this.objectiveProgress)}s`;if(this.objectiveProgress>=this.mission.duration)this.endMission(true)}
  // aim: mouse by default, snaps to the locked target while a lock is held
  updateAim(dt){const p=this.player;
    if(this.lockTarget&&(this.lockTarget.dead||this.lockTarget.group.position.distanceTo(p.group.position)>45)){this.lockTarget=null;this.hud.toast('LOCK LOST',true)}
    // long-press RMB acquires a lock on the enemy nearest the cursor
    if(this.input.rightHeldFor()>.35&&!this.rightLockDone){this.rightLockDone=true;const target=this.enemyNearCursor();if(target){this.lockTarget=target;this.audio.play('pickup',1.8);this.hud.toast('TARGET LOCKED')}else this.hud.toast('NO TARGET NEAR CURSOR',true)}
    if(!this.input.mouse.right)this.rightLockDone=false;
    if(this.lockTarget){const dir=this.lockTarget.group.position.clone().sub(p.group.position).setY(0);if(dir.lengthSq()>.01)p.aim.lerp(dir.normalize(),.5).normalize()}
    else{const rect=this.renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((this.input.mouse.x-rect.left)/rect.width*2-1,-((this.input.mouse.y-rect.top)/rect.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,this.camera);const point=new THREE.Vector3();if(ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),point)){point.sub(p.group.position).setY(0);if(point.lengthSq()>.01)p.aim.lerp(point.normalize(),.32).normalize()}}
    p.group.rotation.y=Math.atan2(p.aim.x,p.aim.z)}
  enemyNearCursor(){let best=null,bestD=170;for(const e of this.enemies){if(e.dead)continue;const s=this.toScreen(e.group.position);if(!s)continue;const d=Math.hypot(s.x-this.input.mouse.x,s.y-this.input.mouse.y);if(d<bestD){bestD=d;best=e}}return best}
  toScreen(position){const v=position.clone().add(new THREE.Vector3(0,1.6,0)).project(this.camera);if(v.z>1)return null;return{x:(v.x+1)/2*innerWidth,y:(1-v.y)/2*innerHeight}}
  // cursor raycast: crosshair goes red over enemies, tooltip shows unit intel
  updateHover(){const rect=this.renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((this.input.mouse.x-rect.left)/rect.width*2-1,-((this.input.mouse.y-rect.top)/rect.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,this.camera);const hits=ray.intersectObjects(this.scene.children,true);let found=null;for(const h of hits){const e=h.object.userData?.entity;if(e&&!e.dead&&['unit','vehicle','turret','factory','wildlife'].includes(e.type)){found=e;break}}this.hoverEntity=found;const overEnemy=found&&found.team==='red';this.hud.setCrosshair(this.input.mouse.x,this.input.mouse.y,overEnemy,Boolean(this.lockTarget));this.hud.showInfo(found,this.input.mouse.x,this.input.mouse.y)}
  handleInteraction(){const p=this.player;if(p.carriedCrate){if(this.builder.distanceTo(p.group.position)<3.6)this.hud.prompt('E · STACK CRATE ON D-BUILDER');else this.hud.prompt('E · DROP CRATE  ·  F · MATERIALIZE');if(this.input.consume('KeyE')){if(this.builder.distanceTo(p.group.position)<3.6){if(!this.builder.place(p.carriedCrate,p.group.position)){this.hud.toast('PAD FULL',true);return}this.audio.play('build',1.3)}else{p.carriedCrate.carried=false;p.carriedCrate.group.position.copy(p.group.position).addScaledVector(p.aim,1.6);p.carriedCrate.group.position.y=0;p.carriedCrate.group.rotation.set(0,0,0)}p.carriedCrate=null;this.audio.play('pickup',.8)}return}
    let nearest=null,dist=p.magneticGloves?3.6:2.35;for(const c of this.world.crates){if(c.carried||c.placed||c.falling)continue;const d=c.group.position.distanceTo(p.group.position);if(d<dist){dist=d;nearest=c}}
    const nearBuilder=this.builder.distanceTo(p.group.position)<4.2,recipe=nearBuilder?this.builder.recipe():null;
    this.hud.prompt(nearest?`E · CARRY ${nearest.crateType.name.toUpperCase()}${nearBuilder&&recipe?`  ·  F · ${recipe.label}`:''}`:recipe?`F · MATERIALIZE ${recipe.label}`:nearBuilder&&this.builder.count()?'STACK INCOMPLETE — MATCH A COMBO':'');
    if(nearest&&this.input.consume('KeyE')){nearest.carried=true;p.carriedCrate=nearest;this.audio.play('pickup')}}
  switchPlayer(){if(this.player.carriedCrate){this.hud.toast('DROP THE CRATE FIRST',true);return}const controllable=this.allies.filter(e=>e.type==='unit'&&!e.dead);if(controllable.length<2)return;const next=controllable[(controllable.indexOf(this.player)+1)%controllable.length];this.player.player=false;next.player=true;next.ammo=next.ammo??60;this.player=next;this.hud.toast(`${next.classDef.name.toUpperCase()} SELECTED`)}
  setCloak(entity,enabled){entity.group.traverse(o=>{if(!o.isMesh||!o.material)return;o.material.transparent=enabled;o.material.opacity=enabled?.24:1;o.material.depthWrite=!enabled;o.material.needsUpdate=true})}
  useAbility(){const p=this.player;
    if(p.active){if(p.abilityCooldown>0||p.mp<p.active.cost){this.hud.toast('SKILL NOT READY',true);return}this.executeActiveSkill(p);return}
    if(p.abilityCooldown>0||p.mp<p.classDef.cost){this.hud.toast('ABILITY NOT READY',true);return}p.mp-=p.classDef.cost;p.abilityCooldown=p.classDef.cooldown;switch(p.classId){case 'scout':p.statusTimer=4;break;case 'medic':{const ring=new THREE.Mesh(new THREE.RingGeometry(.8,6,24),new THREE.MeshBasicMaterial({color:0x67ffc4,transparent:true,opacity:.35,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.copy(p.group.position).setY(.09);this.scene.add(ring);this.abilityZones.push({type:'heal',owner:p,mesh:ring,life:6,tick:0});break}case 'sniper':p.cloakTimer=6;p.nextShotMultiplier=2.5;this.setCloak(p,true);break;case 'gunner':p.overdriveTimer=4;break;case 'explosives':for(let i=-2;i<=2;i++){const dir=p.aim.clone().applyAxisAngle(new THREE.Vector3(0,1,0),i*.16);this.combat.spawn(p,dir,{...WEAPONS.grenade,damage:36});}break;case 'commando':this.combat.radial(p.group.position,7,55,p,16);p.velocity.addScaledVector(p.aim,-4);break;case 'officer':for(const a of this.allies)if(!a.dead&&a.group.position.distanceTo(p.group.position)<12)a.rallyTimer=8;break;case 'saboteur':for(const e of this.enemies)if(!e.dead&&e.group.position.distanceTo(p.group.position)<10){e.stun=e.type==='vehicle'?5:1.8;if(Number.isFinite(e.mp))e.mp=0}this.particles.burst(p.group.position.clone().add(new THREE.Vector3(0,1,0)),0x86c8ff,30,7);break;case 'heavy':p.barrierTimer=6;break;case 'engineer':{const turret=this.factory.createTurret('blue',p.group.position.clone().addScaledVector(p.aim,2.2));this.allies.push(turret);this.entities.push(turret);break}}this.hud.toast(p.classDef.ability.toUpperCase());this.particles.burst(p.group.position.clone().add(new THREE.Vector3(0,1,0)),TEAM.BLUE,18,4)}
  // the 20 Active Skills carried by Special Destructos
  executeActiveSkill(u){const skill=u.active;if(!skill||u.abilityCooldown>0||u.mp<skill.cost)return;u.mp-=skill.cost;u.abilityCooldown=skill.cooldown;const pos=u.group.position,foes=(u.team==='blue'?this.enemies:this.allies).filter(e=>!e.dead),friends=(u.team==='blue'?this.allies:this.enemies).filter(e=>!e.dead);
    switch(skill.id){
      case 'fireball':this.combat.spawn(u,u.aim,{...WEAPONS.rocket,damage:60,speed:22,color:0xff8a2c});break;
      case 'blink':this.particles.burst(pos.clone().add(new THREE.Vector3(0,1,0)),0x9fe8ff,16,5);u.group.position.addScaledVector(u.aim,8);this.world.clamp(u.group.position);this.particles.burst(u.group.position.clone().add(new THREE.Vector3(0,1,0)),0x9fe8ff,16,5);break;
      case 'healburst':for(const f of friends)if(f.group.position.distanceTo(pos)<8&&Number.isFinite(f.maxHp)){f.hp=Math.min(f.maxHp,f.hp+40);this.spawnDamageNumber(f.group.position,'+40','heal')}this.particles.burst(pos.clone().add(new THREE.Vector3(0,1,0)),0x67ffc4,26,6);break;
      case 'shockwave':this.combat.radial(pos,6,30,u,14);break;
      case 'decoy':{const d=this.factory.createUnit(u.classId,u.team,pos.clone().addScaledVector(u.aim,2));d.hp=d.maxHp=60;d.weapon={...WEAPONS.pistol,range:0};d.stationary=true;d.decoy=true;(u.team==='blue'?this.allies:this.enemies).push(d);this.entities.push(d);break}
      case 'frenzy':u.frenzyTimer=5;break;
      case 'icenova':for(const f of foes)if(f.group.position.distanceTo(pos)<7){f.freeze=2.5;this.spawnDamageNumber(f.group.position,'FROZEN','status')}this.particles.burst(pos.clone().add(new THREE.Vector3(0,.6,0)),0x9fe8ff,32,8);break;
      case 'magnetpull':for(const c of this.world.crates){if(c.carried||c.placed||c.falling)continue;if(c.group.position.distanceTo(pos)<12){const dir=pos.clone().sub(c.group.position).setY(0).normalize();c.group.position.add(dir.multiplyScalar(Math.max(0,c.group.position.distanceTo(pos)-2)))}}break;
      case 'smokescreen':for(const f of foes)if(f.group.position.distanceTo(pos)<9)f.fireCooldown=Math.max(f.fireCooldown,2.5);this.particles.burst(pos.clone().add(new THREE.Vector3(0,1,0)),0x8b93a5,44,5);break;
      case 'sentry':{const t=this.factory.createTurret(u.team,pos.clone().addScaledVector(u.aim,2.2));(u.team==='blue'?this.allies:this.enemies).push(t);this.entities.push(t);break}
      case 'minefield':for(let i=0;i<4;i++){const dir=new THREE.Vector3(Math.sin(i*1.57+.7),0,Math.cos(i*1.57+.7));this.combat.spawn(u,dir,WEAPONS.mine)}break;
      case 'dashstrike':u.velocity.addScaledVector(u.aim,18);this.combat.radial(pos.clone().addScaledVector(u.aim,2),3,25,u,6);break;
      case 'groundpound':u.verticalVelocity=8;this.combat.radial(pos,5,40,u,12);break;
      case 'barrierdome':u.barrierTimer=6;break;
      case 'chainlightning':{let hit=0;for(const f of foes.sort((a,b)=>a.group.position.distanceToSquared(pos)-b.group.position.distanceToSquared(pos))){if(hit>=4||f.group.position.distanceTo(pos)>12)break;this.combat.applyDamage(f,25,u,f.group.position.clone().sub(pos).normalize(),3);this.particles.burst(f.group.position.clone().add(new THREE.Vector3(0,1.4,0)),0xaef3ff,10,4);hit++}break}
      case 'rocketbarrage':for(let i=-2;i<=2;i++){const dir=u.aim.clone().applyAxisAngle(new THREE.Vector3(0,1,0),i*.14);this.combat.spawn(u,dir,{...WEAPONS.rocket,damage:45})}break;
      case 'snaretrap':{const f=foes.sort((a,b)=>a.group.position.distanceToSquared(pos)-b.group.position.distanceToSquared(pos))[0];if(f&&f.group.position.distanceTo(pos)<10){f.freeze=3;this.spawnDamageNumber(f.group.position,'SNARED','status')}break}
      case 'warcry':for(const f of friends)if(f.group.position.distanceTo(pos)<12){f.rallyTimer=8;if(f.buffs)f.buffs.damage=Math.max(f.buffs.damage,8)}this.particles.burst(pos.clone().add(new THREE.Vector3(0,1,0)),0xffd23f,26,7);break;
      case 'quake':for(const f of foes){const rel=f.group.position.clone().sub(pos),along=rel.dot(u.aim);if(along>0&&along<14&&rel.clone().addScaledVector(u.aim,-along).length()<3){f.stun=2;this.combat.applyDamage(f,20,u,u.aim,4)}}this.particles.burst(pos.clone().addScaledVector(u.aim,4).add(new THREE.Vector3(0,.4,0)),0xc9a45c,30,8);break;
      case 'overcharge':u.overchargeShots=3;break;
    }
    if(u===this.player||u.team==='blue')this.hud.toast(skill.name.toUpperCase());this.particles.burst(pos.clone().add(new THREE.Vector3(0,1,0)),u.team==='blue'?TEAM.BLUE:TEAM.RED,14,4)}
  updateAbilityZones(dt){for(let i=this.abilityZones.length-1;i>=0;i--){const z=this.abilityZones[i];z.life-=dt;z.tick-=dt;z.mesh.material.opacity=Math.max(0,z.life/6*.35);z.mesh.rotation.z+=dt*.3;if(z.tick<=0){z.tick=.5;for(const a of this.allies)if(!a.dead&&a.group.position.distanceTo(z.mesh.position)<6)a.hp=Math.min(a.maxHp,a.hp+7.5)}if(z.life<=0){this.scene.remove(z.mesh);z.mesh.geometry.dispose();z.mesh.material.dispose();this.abilityZones.splice(i,1)}}}
  // builder output: weapons, destructos (normal/elite/special) or tanks — quality scales with crate rarity tier
  handleBuild(recipe,tier=0,builder=this.builder){const team=builder.team,isBlue=team==='blue';this.audio.play('build');const pos=builder.pad.clone().add(new THREE.Vector3(0,0,isBlue?4:-4));pos.y=0;const tierLabel=['','UNCOMMON ','RARE ','LEGENDARY '][tier]||'';
    if(recipe.output==='unit'){
      const grade=recipe.grade||'normal',classPool={normal:['scout','gunner','medic'],elite:['commando','sniper','officer','explosives'],special:['commando','officer','heavy','engineer','saboteur']}[grade],classId=pick(classPool);
      const opts={grade};if(grade==='elite'||grade==='special')opts.passive=pick(PASSIVE_SKILLS);if(grade==='special')opts.active=pick(ACTIVE_SKILLS);
      const unit=this.addUnit(classId,team,pos,opts);
      if(tier>0){unit.maxHp=Math.round(unit.maxHp*(1+tier*.18));unit.hp=unit.maxHp;unit.classDef={...unit.classDef,speed:unit.classDef.speed*(1+tier*.06)};unit.group.scale.multiplyScalar(1+tier*.05)}
      if(isBlue)this.hud.toast(`${tierLabel}${recipe.label}${opts.passive?` · ${opts.passive.name.toUpperCase()}`:''}${opts.active?` + ${opts.active.name.toUpperCase()}`:''} READY`)}
    else if(recipe.output==='vehicle'){const tank=this.factory.createTank(team,pos,recipe.mega);if(tier>0){tank.maxHp=Math.round(tank.maxHp*(1+tier*.15));tank.hp=tank.maxHp}(isBlue?this.allies:this.enemies).push(tank);this.entities.push(tank);if(isBlue)this.hud.toast(`${tierLabel}${recipe.label} READY`)}
    else{const weaponId=recipe.weapons[Math.min(tier,recipe.weapons.length-1)],weapon={...WEAPONS[weaponId],damage:Math.round(WEAPONS[weaponId].damage*(1+tier*.15))};
      if(isBlue){this.player.weaponId=weaponId;this.player.weapon=weapon;this.player.weaponTier=tier;this.player.ammo=(this.player.ammo||0)+50;this.hud.toast(`${tierLabel}${weapon.name.toUpperCase()} EQUIPPED (+50 AMMO)`)}
      else{const red=this.enemies.find(e=>e.type==='unit'&&!e.dead);if(red){red.weaponId=weaponId;red.weapon=weapon}}}
    if(isBlue)this.particles.burst(pos.clone().add(new THREE.Vector3(0,1,0)),TEAM.YELLOW,30,8);
    if(this.mission.type==='build'&&isBlue&&recipe.output==='unit'&&recipe.count>=4)setTimeout(()=>this.endMission(true),700);
    return true}
  handleDamage(target,amount,source){if(amount<=0){if(target.passive?.id==='lucky')this.spawnDamageNumber(target.group.position,'DODGE','status');return}
    const kind=target===this.player?'hurt-player':target.team==='red'?'hurt-enemy':target.team==='blue'?'hurt-ally':'hurt';
    this.spawnDamageNumber(target.group.position,String(Math.max(1,Math.round(amount))),kind);
    if(target===this.player)this.hud.damage()}
  spawnDamageNumber(position,text,kind){const s=this.toScreen(position);if(s)this.hud.damageNumber(s.x,s.y,text,kind)}
  handleDeath(target,source){this.audio.play('explosion',target.type==='factory'?.7:1.1);if(this.lockTarget===target)this.lockTarget=null;if(target.carriedCrate){target.carriedCrate.carried=false;target.carriedCrate=null}if(target===this.player){const next=this.allies.find(e=>e.type==='unit'&&!e.dead);if(next){target.player=false;next.player=true;next.ammo=next.ammo??60;this.player=next;this.hud.toast(`${next.classDef.name.toUpperCase()} TAKING COMMAND`)}else setTimeout(()=>this.endMission(false),700)}if(target===this.world.redFactory&&this.mission.type==='assault'){setTimeout(()=>this.endMission(true),900);return}if(target===this.world.redFactory)this.hud.toast('ENEMY REINFORCEMENTS DISABLED');if(target.type==='unit'&&target.team==='red'){this.kills++;if(source)source.kills=(source.kills||0)+1}if(target.type==='wildlife'&&target.kind==='slime'){const charged=this.factory.createCrate(target.group.position.clone(),'blue');this.world.crates.push(charged)}gsap.to(target.group.scale,{x:.05,y:.05,z:.05,duration:.45,ease:'back.in(2)',onComplete:()=>{target.group.visible=false}})}
  updateCamera(dt){const desired=this.player.group.position.clone().add(new THREE.Vector3(0,21,20));desired.y=21+this.player.group.position.y*.3;this.camera.position.lerp(desired,1-Math.pow(.001,dt));const target=this.player.group.position.clone().add(new THREE.Vector3(0,1.2,2));this.camera.lookAt(target)}
  endMission(won){if(this.state!=='mission')return;const reward=won?this.mission.reward+this.kills*35:Math.floor(this.kills*12);this.save.recordMission(won,this.kills,reward);this.endRuntime();this.state='results';this.screen.innerHTML=`<main class="menu mission-end"><span class="eyebrow">${this.mission.name.toUpperCase()}</span><h2>${won?'VICTORY':'SQUAD LOST'}</h2><div class="stat-row"><div><strong>${this.kills}</strong><span>ELIMINATIONS</span></div><div><strong>${Math.floor(this.elapsed/60)}:${String(Math.floor(this.elapsed%60)).padStart(2,'0')}</strong><span>TIME</span></div><div><strong>${reward}</strong><span>CHIPS</span></div></div><div class="menu-actions"><button class="btn primary" data-action="hub">RETURN TO HUB</button><button class="btn" data-action="missions">MISSION BOARD</button></div></main>`}
  endRuntime(){this.input.enabled=false;this.input.mouse.down=false;this.hud.show(false);this.hud.showInfo(null)}
  disposeScene(){if(!this.scene)return;this.scene.traverse(o=>{if(o.geometry)o.geometry.dispose?.();if(o.material&&!Array.isArray(o.material))o.material.dispose?.()});this.scene.clear();this.materials?.dispose?.();this.world?.dispose?.()}
  resize(){const w=innerWidth,h=innerHeight;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h)}
  loop(){if(this.running)return;this.running=true;const frame=()=>{requestAnimationFrame(frame);const time=performance.now()/1000,dt=time-this.lastFrame;this.lastFrame=time;this.update(dt,time);this.renderer.render(this.scene,this.camera)};frame()}
}
