import * as THREE from 'three';
import { createWearableCosmetic, cosmeticVisual } from './CosmeticModels.js';

const materialKit = {
  color(color, options = {}) {
    const config = { color, metalness: options.metalness ?? .55, roughness: options.roughness ?? .32, emissive: options.emissive ?? 0x000000, emissiveIntensity: options.emissiveIntensity ?? 0, opacity: options.opacity ?? 1 };
    if (options.transparent !== undefined) config.transparent = options.transparent;
    return new THREE.MeshStandardMaterial(config);
  },
};
const part = (geometry, material, position) => { const mesh=new THREE.Mesh(geometry,material);mesh.position.set(...position);mesh.castShadow=mesh.receiveShadow=true;return mesh };

export class MarketplacePreview {
  constructor(canvas) {
    this.canvas=canvas;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x07121c);this.scene.fog=new THREE.Fog(0x07121c,8,18);
    this.camera=new THREE.PerspectiveCamera(38,1,.1,50);this.camera.position.set(0,2.5,7.2);this.camera.lookAt(0,.25,0);this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;
    this.root=new THREE.Group();this.root.position.y=-1.35;this.scene.add(this.root);this.scene.add(new THREE.HemisphereLight(0x9eeaff,0x11131c,2.4));const key=new THREE.DirectionalLight(0xffffff,4.8);key.position.set(4,7,5);this.scene.add(key);const rim=new THREE.PointLight(0xffd23f,18,10);rim.position.set(-4,2,-2);this.scene.add(rim);
    const floor=new THREE.Mesh(new THREE.CylinderGeometry(2.5,2.7,.24,48),new THREE.MeshStandardMaterial({color:0x152536,metalness:.82,roughness:.26}));floor.position.y=-.1;floor.receiveShadow=true;this.root.add(floor);const ring=new THREE.Mesh(new THREE.TorusGeometry(2.25,.055,8,64),new THREE.MeshBasicMaterial({color:0x47e7ff}));ring.rotation.x=Math.PI/2;ring.position.y=.04;this.root.add(ring);
    this.modelRoot=new THREE.Group();this.root.add(this.modelRoot);this.rotation=.25;this.targetRotation=.25;this.pitch=0;this.dragging=false;this.autoRotate=true;this.bind();this.resize();if(globalThis.ResizeObserver){this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas)}this.animate();
  }
  bind(){this.down=e=>{this.dragging=true;this.autoRotate=false;this.lastX=e.clientX;this.lastY=e.clientY;this.canvas.setPointerCapture?.(e.pointerId)};this.move=e=>{if(!this.dragging)return;this.targetRotation+=(e.clientX-this.lastX)*.012;this.pitch=THREE.MathUtils.clamp(this.pitch+(e.clientY-this.lastY)*.004,-.2,.22);this.lastX=e.clientX;this.lastY=e.clientY};this.up=()=>this.dragging=false;this.wheel=e=>{e.preventDefault();this.camera.position.z=THREE.MathUtils.clamp(this.camera.position.z+Math.sign(e.deltaY)*.45,5.8,9.2)};this.canvas.addEventListener('pointerdown',this.down);this.canvas.addEventListener('pointermove',this.move);this.canvas.addEventListener('pointerup',this.up);this.canvas.addEventListener('pointercancel',this.up);this.canvas.addEventListener('wheel',this.wheel,{passive:false})}
  resize(){const w=Math.max(1,this.canvas.clientWidth),h=Math.max(1,this.canvas.clientHeight);this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
  clear(){while(this.modelRoot.children.length){const child=this.modelRoot.children.pop();child.traverse?.(o=>{o.geometry?.dispose?.();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose?.());else o.material?.dispose?.()})}}
  makeDestructo(skinId){const colors=cosmeticVisual(skinId),bodyMat=materialKit.color(skinId?colors.primary:0x2fb4ff),accent=materialKit.color(skinId?colors.secondary:0xf2f7ff,{emissive:skinId?colors.secondary:0,emissiveIntensity:skinId ? .4 : 0}),dark=materialKit.color(0x1b2430);const unit=new THREE.Group();unit.name='preview-destructo';unit.add(part(new THREE.BoxGeometry(1.1,1.25,.84),bodyMat,[0,1.34,0]));unit.add(part(new THREE.SphereGeometry(.57,16,10),bodyMat,[0,2.25,0]));const visor=part(new THREE.BoxGeometry(.78,.2,.1),accent,[0,2.29,.52]);unit.add(visor);for(const x of [-.68,.68]){unit.add(part(new THREE.CylinderGeometry(.17,.19,.92,8),bodyMat,[x,1.4,0]));unit.add(part(new THREE.SphereGeometry(.2,8,6),dark,[x,.85,.08]))}for(const x of [-.33,.33]){unit.add(part(new THREE.CylinderGeometry(.19,.21,.78,8),dark,[x,.52,0]));unit.add(part(new THREE.BoxGeometry(.43,.24,.62),dark,[x,.16,.08]))}return unit}
  makeCrate(item,rarity='brown'){
    const palette={brown:[0xb07840,0x7a4e26],yellow:[0xffd23f,0xc79415],blue:[0x58c8ff,0x1f7fc0],red:[0xff4d5e,0xa8202f]}[rarity]||[0xb07840,0x7a4e26],model=item.kind==='crateModel'?item.visual.model:'standard',bodyMat=materialKit.color(palette[0],{metalness:rarity==='brown'?.18:.62,roughness:rarity==='brown'?.7:.38}),bandMat=materialKit.color(palette[1],{metalness:.72,roughness:.28}),group=new THREE.Group();
    const geometry=model==='bulwark'?new THREE.BoxGeometry(1.7,1.25,1.45):model==='reactor'?new THREE.CylinderGeometry(.88,.96,1.5,8):model==='capsule'?new THREE.CapsuleGeometry(.75,.4,6,12):new THREE.BoxGeometry(1.5,1.5,1.5),body=part(geometry,bodyMat,[0,.86,0]);group.add(body);
    if(model==='reactor'||model==='capsule'){for(const y of [.3,1.4]){const ring=part(new THREE.TorusGeometry(model==='reactor'?.91:.76,.07,6,model==='reactor'?8:16),bandMat,[0,y,0]);ring.rotation.x=Math.PI/2;group.add(ring)}}else{const top=part(new THREE.BoxGeometry(model==='bulwark'?1.76:1.56,.1,.16),bandMat,[0,model==='bulwark'?1.5:1.64,0]);group.add(top);for(const x of [-.55,.55])group.add(part(new THREE.BoxGeometry(.13,model==='bulwark'?1.3:1.55,.13),bandMat,[x,.86,.7]));}
    if(item.kind==='crateTexture'){const texture=item.visual.texture;if(texture==='reactorTrace'){for(const x of [-.42,0,.42])group.add(part(new THREE.BoxGeometry(.04,.8,.04),bandMat,[x,.86,.76]))}else if(texture==='hazardGrid'){for(const x of [-.48,0,.48]){const stripe=part(new THREE.BoxGeometry(.1,1.05,.04),bandMat,[x,.86,.76]);stripe.rotation.z=-.35;group.add(stripe)}}else if(texture==='rivetCamo'){for(const [x,y] of [[-.45,.5],[.45,.5],[-.45,1.22],[.45,1.22]])group.add(part(new THREE.SphereGeometry(.055,8,6),bandMat,[x,y,.78]))}else{for(const y of [.48,.86,1.24])group.add(part(new THREE.BoxGeometry(1.12,.045,.04),bandMat,[0,y,.78]))}}
    if(rarity==='blue'||rarity==='red'){const gem=part(new THREE.OctahedronGeometry(.2,0),materialKit.color(0xffffff,{emissive:palette[0],emissiveIntensity:1.6}),[0,1.85,0]);gem.name='animated-core';group.add(gem)}return group;
  }
  showcase(item){const {primary,secondary,model}=item.visual,main=materialKit.color(primary,{emissive:primary,emissiveIntensity:.8}),accent=materialKit.color(secondary,{emissive:secondary,emissiveIntensity:1.5});const group=new THREE.Group();group.name='effect-showcase';if(item.kind==='teamBase'){group.position.set(-1.25,.12,-.7);group.scale.setScalar(.55);group.add(part(new THREE.CylinderGeometry(1.4,1.8,.45,10),main,[0,.22,0]));group.add(part(new THREE.BoxGeometry(2.1,1.7,1.7),main,[0,1.25,0]));const core=part(new THREE.OctahedronGeometry(.48,0),accent,[0,2.35,0]);core.name='animated-core';group.add(core)}else{for(let i=0;i<9;i++){const shard=part(model==='heart'?new THREE.OctahedronGeometry(.12,0):new THREE.IcosahedronGeometry(.09+i%3*.035,0),i%2?main:accent,[0,1.4,0]);const a=i/9*Math.PI*2;shard.userData.orbit={a,r:.75+(i%3)*.22,speed:.7+(i%4)*.18,y:1.2+(i%3)*.36};group.add(shard)}const coreGeometry=item.kind==='projectile'?(model==='plasma'?new THREE.IcosahedronGeometry(.3,2):model==='pellet'?new THREE.SphereGeometry(.2,10,7):new THREE.CapsuleGeometry(.16,.7,5,8)):new THREE.IcosahedronGeometry(.35,1),core=part(coreGeometry,accent,[0,1.55,.78]);core.rotation.x=Math.PI/2;core.name='animated-core';group.add(core)}return group}
  setItem(item,equipped={},options={}){this.item=item;this.clear();if(item.kind==='crateTexture'||item.kind==='crateModel'){this.modelRoot.add(this.makeCrate(item,options.crateRarity));this.modelRoot.scale.setScalar(1.15);this.targetRotation+=Math.PI*.08;return}const preview={...equipped};if(['hat','boots','attachment'].includes(item.kind))preview[item.kind]=item.id;if(item.kind==='skin')preview.skin=item.id;const unit=this.makeDestructo(preview.skin);if(preview.hat)unit.add(createWearableCosmetic('hat',preview.hat,materialKit,0x2fb4ff));if(preview.boots)unit.add(createWearableCosmetic('boots',preview.boots,materialKit));if(preview.attachment)unit.add(createWearableCosmetic('attachment',preview.attachment,materialKit));this.modelRoot.add(unit);if(!['hat','boots','attachment','skin'].includes(item.kind))this.modelRoot.add(this.showcase(item));this.modelRoot.scale.setScalar(1);this.targetRotation+=Math.PI*.08}
  toggleSpin(){this.autoRotate=!this.autoRotate;return this.autoRotate}
  animate(){if(this.disposed)return;this.frame=requestAnimationFrame(()=>this.animate());const time=performance.now()/1000;if(this.autoRotate)this.targetRotation+=.004;this.rotation=THREE.MathUtils.lerp(this.rotation,this.targetRotation,.09);this.modelRoot.rotation.y=this.rotation;this.modelRoot.rotation.x=THREE.MathUtils.lerp(this.modelRoot.rotation.x,this.pitch,.08);this.modelRoot.traverse(o=>{if(o.name==='cosmetic-flame'){o.scale.y=.8+Math.sin(time*12+o.position.x*4)*.3;o.material.emissiveIntensity=1.2+Math.sin(time*9)*.35}if(o.name==='animated-core'){o.rotation.y+=.018;o.rotation.x+=.009}if(o.userData?.orbit){const v=o.userData.orbit,a=v.a+time*v.speed;o.position.set(Math.cos(a)*v.r,v.y+Math.sin(a*2)*.12,Math.sin(a)*v.r)}});this.renderer.render(this.scene,this.camera)}
  dispose(){this.disposed=true;cancelAnimationFrame(this.frame);this.observer?.disconnect();this.canvas.removeEventListener('pointerdown',this.down);this.canvas.removeEventListener('pointermove',this.move);this.canvas.removeEventListener('pointerup',this.up);this.canvas.removeEventListener('pointercancel',this.up);this.canvas.removeEventListener('wheel',this.wheel);this.clear();this.renderer.dispose()}
}
