import { beforeEach, describe, expect, it } from 'vitest';
import { MARKETPLACE_COSMETICS, TICKET_BUNDLES, getMarketplaceRotation, marketplacePrice } from '../src/data/marketplaceData.js';
import { SaveSystem } from '../src/game/SaveSystem.js';
import { paypalConfig } from '../server/paypal.js';
import { stepJumpState, JUMP_RULES } from '../src/game/JumpSystem.js';

describe('live cosmetics marketplace',()=>{
  beforeEach(()=>{const memory=new Map();globalThis.localStorage={getItem:key=>memory.get(key)||null,setItem:(key,value)=>memory.set(key,value),clear:()=>memory.clear()}});
  it('ships a large catalog with at least twenty premium legends',()=>{expect(MARKETPLACE_COSMETICS.length).toBeGreaterThanOrEqual(60);expect(MARKETPLACE_COSMETICS.filter(item=>['legendary','mythic'].includes(item.rarity)).length).toBeGreaterThanOrEqual(20)});
  it('caps every premium item at one thousand tickets',()=>{const premium=MARKETPLACE_COSMETICS.filter(item=>item.currency==='tickets');expect(premium.length).toBeGreaterThan(20);expect(Math.max(...premium.map(item=>item.price))).toBeLessThanOrEqual(1000)});
  it('keeps promo-only mythics out of ordinary drops',()=>{const rotation=getMarketplaceRotation(Date.UTC(2026,6,15,12));expect(rotation.drops.every(entry=>!entry.item.promoOnly)).toBe(true);expect(rotation.promos.length).toBe(3);expect(rotation.promos.every(entry=>entry.item.promoOnly)).toBe(true)});
  it('rotates deterministically every three hours',()=>{const time=Date.UTC(2026,6,15,12),first=getMarketplaceRotation(time),same=getMarketplaceRotation(time+1000),next=getMarketplaceRotation(time+3*60*60*1000);expect(first.drops.map(x=>x.item.id)).toEqual(same.drops.map(x=>x.item.id));expect(first.slot).not.toBe(next.slot);expect(first.drops.map(x=>x.item.id)).not.toEqual(next.drops.map(x=>x.item.id))});
  it('applies server-independent promotional display prices',()=>{const rotation=getMarketplaceRotation(Date.UTC(2026,6,15,12)),offer=rotation.drops.find(entry=>entry.discount);expect(marketplacePrice(offer.item,rotation)).toBeLessThan(offer.item.price)});
  it('defines real-money bundles from $0.99 through $99',()=>{expect(TICKET_BUNDLES[0]).toMatchObject({tickets:5,price:'0.99'});expect(TICKET_BUNDLES.at(-1)).toMatchObject({tickets:1000,price:'99.00'})});
  it('targets the creator merchant without exposing server secrets',()=>{const config=paypalConfig({PAYPAL_MODE:'live',PAYPAL_CLIENT_ID:'client-id',PAYPAL_CLIENT_SECRET:'server-only'});expect(config.merchantEmail).toBe('lemonquake@gmail.com');expect(config.enabled).toBe(true);expect(JSON.stringify({enabled:config.enabled,clientId:config.clientId,merchantEmail:config.merchantEmail})).not.toContain('server-only')});
  it('includes Lemon-Quake Boots as marked gameplay gear',()=>{expect(MARKETPLACE_COSMETICS.find(item=>item.id==='lemon-quake-boots')).toMatchObject({kind:'boots',rarity:'legendary',gameplay:expect.stringContaining('Double-jump')})});
  it('boosts the second airborne press and consumes the extra jump',()=>{const state={motion:'airborne',verticalVelocity:-3,jetpackBurn:0,mp:50,doubleJumped:false},input={grounded:false,jumpPressed:true,jumpHeld:false,hasDoubleJump:true,hasJetpack:false,blocked:false,jumpScale:1},jump=stepJumpState(state,input,1/60);expect(jump.secondJumped).toBe(true);expect(jump.doubleJumped).toBe(true);expect(jump.verticalVelocity).toBeCloseTo(JUMP_RULES.doubleJumpVelocity-JUMP_RULES.gravity/60);const repeated=stepJumpState(jump,input,1/60);expect(repeated.secondJumped).toBe(false)});
  it('persists purchase, equip, and favorites state',()=>{const save=new SaveSystem();save.data.tickets=500;expect(save.buyCosmetic('lemon-quake-boots',425,'tickets')).toBe(true);save.equipCosmetic('boots','lemon-quake-boots');save.data.favoriteCosmetics=['lemon-quake-boots'];save.commit();const loaded=new SaveSystem();expect(loaded.data.equipped.boots).toBe('lemon-quake-boots');expect(loaded.data.favoriteCosmetics).toContain('lemon-quake-boots');expect(loaded.data.tickets).toBe(75)});
});
