import crypto from 'node:crypto';
import { TICKET_BUNDLES } from '../src/data/marketplaceData.js';

const json = (res,status,payload) => {res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(payload))};
const paypalBase = mode => mode === 'live' ? 'https://api-m.paypal.com' : 'https://api-m.sandbox.paypal.com';
const publicError = (message,details=[]) => Object.assign(new Error(message),{details});

export function paypalConfig(env=process.env){
  const mode=env.PAYPAL_MODE==='live'?'live':'sandbox',clientId=String(env.PAYPAL_CLIENT_ID||'').trim(),clientSecret=String(env.PAYPAL_CLIENT_SECRET||'').trim(),merchantEmail=String(env.PAYPAL_MERCHANT_EMAIL||'lemonquake@gmail.com').trim();
  return {mode,clientId,clientSecret,merchantEmail,enabled:Boolean(clientId&&clientSecret)};
}

async function accessToken(config){const auth=Buffer.from(`${config.clientId}:${config.clientSecret}`).toString('base64'),response=await fetch(`${paypalBase(config.mode)}/v1/oauth2/token`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'}),data=await response.json();if(!response.ok||!data.access_token)throw publicError('PayPal authentication failed. Check the server credentials.',data.details);return data.access_token}
async function paypalFetch(config,path,options={}){const token=await accessToken(config),response=await fetch(`${paypalBase(config.mode)}${path}`,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','PayPal-Request-Id':options.requestId||crypto.randomUUID(),Prefer:'return=representation',...(options.headers||{})}}),data=await response.json().catch(()=>({}));return{response,data}}
function bundleFor(id){return TICKET_BUNDLES.find(bundle=>bundle.id===id)}
function validateCompletedOrder(order,config){const unit=order?.purchase_units?.[0],bundle=bundleFor(unit?.custom_id),capture=unit?.payments?.captures?.find(entry=>entry.status==='COMPLETED'),payee=String(unit?.payee?.email_address||'').trim().toLowerCase();if(order?.status!=='COMPLETED'||!bundle||!capture)throw publicError('PayPal did not return a completed ticket purchase.');if(payee!==config.merchantEmail.toLowerCase())throw publicError('The captured payment was not routed to the configured creator account.');if(capture.amount?.currency_code!=='USD'||capture.amount?.value!==bundle.price)throw publicError('The captured amount does not match the selected ticket pack.');return{success:true,orderId:order.id,captureId:capture.id,tickets:bundle.tickets,bundleId:bundle.id,status:'COMPLETED',merchant:config.merchantEmail}}

async function createOrder(config,bundleId){const bundle=bundleFor(bundleId);if(!bundle)throw publicError('Unknown ticket pack.');const payload={intent:'CAPTURE',purchase_units:[{reference_id:'DESTRUCTO_TICKETS',custom_id:bundle.id,description:`${bundle.tickets} Destructo Tickets`,payee:{email_address:config.merchantEmail},amount:{currency_code:'USD',value:bundle.price,breakdown:{item_total:{currency_code:'USD',value:bundle.price}}},items:[{name:`${bundle.name} — ${bundle.tickets} Tickets`,description:'Premium in-game currency for Destructo cosmetics',sku:`destructo-${bundle.id}`,unit_amount:{currency_code:'USD',value:bundle.price},quantity:'1',category:'DIGITAL_GOODS'}]}],payment_source:{paypal:{experience_context:{brand_name:'Destructo Marketplace',shipping_preference:'NO_SHIPPING',user_action:'PAY_NOW'}}}};const {response,data}=await paypalFetch(config,'/v2/checkout/orders',{method:'POST',body:JSON.stringify(payload)});if(!response.ok||!data.id)throw publicError('Could not create the PayPal order.',data.details);return{id:data.id,status:data.status}}
async function captureOrder(config,orderId){if(!/^[A-Z0-9-]{8,32}$/i.test(orderId||''))throw publicError('Invalid PayPal order ID.');let result=await paypalFetch(config,`/v2/checkout/orders/${encodeURIComponent(orderId)}/capture`,{method:'POST'});const alreadyCaptured=result.data?.details?.some(detail=>detail.issue==='ORDER_ALREADY_CAPTURED');if(alreadyCaptured)result=await paypalFetch(config,`/v2/checkout/orders/${encodeURIComponent(orderId)}`,{method:'GET'});if(!result.response.ok)throw publicError('PayPal could not capture this order.',result.data?.details);return validateCompletedOrder(result.data,config)}
async function bodyJson(req){return await new Promise((resolve,reject)=>{let raw='';req.on('data',chunk=>{raw+=chunk;if(raw.length>12000){reject(publicError('Request is too large.'));req.destroy()}});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(publicError('Invalid JSON request.'))}});req.on('error',reject)})}

export async function handlePayPalRequest(req,res,env=process.env){const url=new URL(req.url,'http://localhost'),path=url.pathname,config=paypalConfig(env);if(!path.startsWith('/api/paypal/'))return false;res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');try{if(req.method==='GET'&&path==='/api/paypal/config'){json(res,200,{enabled:config.enabled,mode:config.mode,clientId:config.clientId,merchantEmail:config.merchantEmail,bundles:TICKET_BUNDLES});return true}if(!config.enabled){json(res,503,{error:'PayPal checkout is not configured on this server.'});return true}if(req.method==='POST'&&path==='/api/paypal/orders'){const body=await bodyJson(req);json(res,201,await createOrder(config,body.bundleId));return true}const match=path.match(/^\/api\/paypal\/orders\/([^/]+)\/capture$/);if(req.method==='POST'&&match){json(res,200,await captureOrder(config,match[1]));return true}json(res,404,{error:'Payment endpoint not found.'});return true}catch(error){console.error('[PayPal]',error.message,error.details||'');json(res,400,{error:error.message,details:error.details||[]});return true}}
